[package]
name = "const_fn"
version = "0.3.0"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/const_fn"
homepage = "https://github.com/taiki-e/const_fn"
documentation = "https://docs.rs/const_fn"
keywords = ["macros", "attribute", "const", "static"]
categories = ["rust-patterns"]
readme = "README.md"
description = """
An attribute for easy generation of a const function with conditional compilations.
"""

[workspace]
members = ["test_suite"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
syn-mid = "0.5"
